name: Issue Status

on:
  schedule:
    - cron:  '0 6 * * 0-4'
  push:
    branches: [ master ]

jobs:
  sent-telegram-message-issue_status:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Gathering dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv
          sudo pip3 install python-telegram-bot PyGithub
      - name: run bot script
        env:
          BOT_ISSUES_STATUS: ${{ secrets.BOT_ISSUES_STATUS }}
          CHAT_ID_ISSUES_STATUS: ${{ secrets.CHAT_ID_ISSUES_STATUS }}
        run: |
          sudo --preserve-env=BOT_ISSUES_STATUS --preserve-env=CHAT_ID_ISSUES_STATUS \
          python3 issue_statues/bot.py
