name: Open repo PRs

on:
  schedule:
    - cron:  '0 */3 * * *'
  push:
    branches: [ master ]

jobs:
  sent-telegram-message-open-PRs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Gathering dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv
          sudo pip3 install python-telegram-bot PyGithub
      - name: run bot script
        env:
          CHAT_ID_OPEN_PRs: ${{ secrets.CHAT_ID_OPEN_PRs }}
          PRs_TOKEN: ${{ secrets.PRs_TOKEN }}
        run: |
          sudo --preserve-env=CHAT_ID_OPEN_PRs --preserve-env=PRs_TOKEN \
          python3 github_open_prs/bot.py
